name: Choose dotnet version
on:
  workflow_call:
    inputs:
      dotnet_version:
        required: false
        default: "6.0.100"
        type: string

jobs:
  dotnet-build:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      # - name: Install .Net Core
      #   uses: actions/setup-dotnet@v3
      #   with:
      #     dotnet-version: ${{ inputs.dotnet_version }}

      - name: Print dotnet version
        shell: cmd
        run: dotnet --info
  